### ISSUE TITLE
TASK-5: Rewrite RegisterUserHandlerTest to real unit test

### ISSUE THREAD

**Issue by javagurulv** [javagurulv/chat_bot#11]
Check RegisterUserEmailHandlerTest and rewrite RegisterUserHandlerTest to real unit test using Mockito framework.

**Comment by ValerijaI** [comment]
* RegisterUserHandlerTest is rewritten to real unit test using Mockito framework

?? Should test check created users telegramId in test: shouldCreateNewUser?
