### ISSUE TITLE
Create user registration acceptance test

### ISSUE THREAD

**Issue by javagurulv** [javagurulv/chat_bot#7]
I want to test hole user registration process in one acceptance test.
Use RegisterUserCommandTest as example and implement one test.
This test must invoke in one test case sequentially following commands:
- RegisterUserCommand
- RegisterUserFirstNameCommand
- RegisterUserLastNameCommand
- RegisterUserPhoneCommand
- RegisterUserEmailCommand 
and then check results in db.

**Comment by ValerijaI** [comment]
* Created test UserRegistrationAcceptanceTest
* This tests whole user registration process in one acceptance test.
*Test invokes in one test case sequentially following commands:
RegisterUserCommand
RegisterUserFirstNameCommand
RegisterUserLastNameCommand
RegisterUserPhoneCommand
RegisterUserEmailCommand
and then check results in db.
